### ISSUE TITLE
Axios

### ISSUE THREAD

**Issue by lucasjaviluna** [gaaston14/TP_CertificacionDeTareas#1]
[Middle]
	Acá no debería usarse la instancia de axios de http-common??
	https://vscode.dev/github/gaaston14/TP_CertificacionDeTareas/blob/main/app/src/views/EditTask.vue#L32
	https://vscode.dev/github/gaaston14/TP_CertificacionDeTareas/blob/main/app/src/views/ListCertifications.vue#L126

**Comment by matiaschiodo** [comment]
Resuelto en [commit](https://github.com/gaaston14/TP_CertificacionDeTareas/commit/b2e8f4e05771241fb49126157d2034f817467ab3)
